### ISSUE TITLE
Over-flowing of text from the boxes

### ISSUE THREAD

**Issue by Bharadwajshivam28** [FOSS-Community/Community-Hub#3]
I have noticed one thing that when we go to https://docs.fosscu.org/Docs (or click on docs button) then i saw that text are overflowing form the box they are going out of the box.. We have to fix it asap..

Please assign to me so i can fix it @akshatcoder-hash 

Dropping the screenshot -

![Screenshot from 2023-05-01 13-50-50](https://user-images.githubusercontent.com/108119109/235428961-fd1e3637-a146-49ee-a01d-0f9fed527807.png)

![Screenshot from 2023-05-01 13-30-58](https://user-images.githubusercontent.com/108119109/235428997-76845367-b1b6-47e1-88dd-5f4e8dac1bf5.png)

![Screenshot from 2023-05-01 13-31-05](https://user-images.githubusercontent.com/108119109/235428999-fce1b4b3-e4c8-4a92-a587-f5add0bfe3d2.png)

![Screenshot from 2023-05-01 13-31-15](https://user-images.githubusercontent.com/108119109/235429000-f04b7424-a658-4af7-ae1a-301e75a7afec.png)

![Screenshot from 2023-05-01 13-31-45](https://user-images.githubusercontent.com/108119109/235429002-32b3f3f7-4e1b-404e-a8de-65a2a515513d.png)

**Comment by akshatcoder-hash** [comment]
Assigned you! @Bharadwajshivam28

**Comment by Bharadwajshivam28** [comment]
thanks sir

**Comment by Bharadwajshivam28** [comment]
Close this issue sir as it is completed

**Comment by vivekpal1** [comment]
@Bharadwajshivam28 You can add the thumbnail on each of these. Because this design is meant for thumbnails.

design and add the banner like this sample...

```md
---
title: "Sample Page"
description: "This is a sample"
banner: "../Banners/sample.png"
tags: ["Sample"]
date: 3 May 2024
position: 1
---
```

**Comment by Bharadwajshivam28** [comment]
> @Bharadwajshivam28 You can add the thumbnail on each of these. Because this design is meant for thumbnails.
> 
> design and add the banner like this sample...
> 
> ```md
> ---
> title: "Sample Page"
> description: "This is a sample"
> banner: "../Banners/sample.png"
> tags: ["Sample"]
> date: 3 May 2024
> position: 1
> ---
> ```

Okay sir

**Comment by akshatcoder-hash** [comment]
#10  fixes this
